version: '3'
services:
 db:
  image: mysql:latest
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: tpachato
  ports:
   - "3306:3306"
  volumes:
   - 'db_data:/var/lib/mysql:rw'
 tp-achat-app:
  build: .
  ports:
   - "8089:8089"
  depends_on:
   - db
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tpachato?useSSL=false&allowPublicKeyRetrieval=true
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: root
   SPRING.JPA.PROPRETIES.HIBERNATE.DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
   SPRING_JPA_HIBERNATE_DDL_AUTO: update
volumes:
 db_data:
