#version: '2'
#services:
 #backen:
  #image: mayari94/test
#  build: .
 # ports:
  #- "8081:8081"

version: '3'
services:
 db:
  image: mysql:latest
  #restart: always
  environment:
   #MYSQL_ROOT_HOST: 172.20.10.6
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: tpachato
  ports:
   - "3306:3306"
  volumes:
   #- ./mysql_data:/var/lib/mysql:rw
   - 'db_data:/var/lib/mysql:rw'
 tp-achat-app:
  build: .
  #image: tpachat-app
  ports:
   - "8089:8089"
  networks:
   my-network:
    - ipv4_address: 192.168.1.10
  depends_on:
   - db
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tpachato?useSSL=false&allowPublicKeyRetrieval=true
   #SPRING_DATASOURCE_URL: jdbc:mysql://172.20.10.6:3306/tpachato?useSSL=false&allowPublicKeyRetrieval=true
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: root
   SPRING.JPA.PROPRETIES.HIBERNATE.DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
   SPRING_JPA_HIBERNATE_DDL_AUTO: update
networks:
 my-network:
  ipam:
   config:
    -subnet: 192.168.1.0/24
volumes:
 db_data:


